Repository dataforgoodfr/13_potentiel_solaire, pull requests merged in 2025-03, with the labels that each got.

#61 Feature: fonctions pour récupérer les flux MNS et MNT sur une géométrie donnée
  algorithme/data/.gitignore
  algorithme/notebooks/exports/wns_hauteur.md
  algorithme/notebooks/exports/wns_hauteur_files/wns_hauteur_10_1.png
  algorithme/notebooks/exports/wns_hauteur_files/wns_hauteur_11_1.png
  algorithme/notebooks/exports/wns_hauteur_files/wns_hauteur_12_2.png
  algorithme/notebooks/exports/wns_hauteur_files/wns_hauteur_14_0.png
  algorithme/notebooks/exports/wns_hauteur_files/wns_hauteur_14_1.png
  algorithme/notebooks/exports/wns_hauteur_files/wns_hauteur_15_1.png
  algorithme/notebooks/exports/wns_hauteur_files/wns_hauteur_16_0.png
  algorithme/notebooks/exports/wns_hauteur_files/wns_hauteur_18_1.png
  algorithme/notebooks/exports/wns_hauteur_files/wns_hauteur_19_0.png
  algorithme/notebooks/exports/wns_hauteur_files/wns_hauteur_22_0.png
  algorithme/notebooks/exports/wns_hauteur_files/wns_hauteur_8_1.png
  algorithme/notebooks/exports/wns_hauteur_files/wns_hauteur_8_2.png
  algorithme/notebooks/exports/wns_hauteur_files/wns_hauteur_9_1.png
  algorithme/notebooks/wms_potentiel_solaire.ipynb
  algorithme/notebooks/wns_hauteur.ipynb
  algorithme/poetry.lock
  algorithme/potentiel_solaire/features/roof_attributes.py
  algorithme/pyproject.toml
Labels: must have

#69 [FRONT] feat: use env for database file config + split sql
  application/.env.template
  application/.gitignore
  application/README.md
  application/app/lib/duckdb.ts
  application/app/models/communes.ts
  application/app/models/departements.ts
  application/app/models/regions.ts
  application/database/export-geojson.sql
  application/database/prepare-JDD-test.sql
Labels: enhancement, frontend

#97 Feature/pvgis api
  algorithme/notebooks/analyse_abaque_pour_api_pvgis.ipynb
  algorithme/notebooks/analyse_qualite_resultats_pipeline.ipynb
  algorithme/notebooks/pipeline_algorithme.ipynb
  algorithme/potentiel_solaire/aggregate.py
  algorithme/potentiel_solaire/constants.py
  algorithme/potentiel_solaire/features/pvgis_api.py
  algorithme/potentiel_solaire/features/roof_attributes.py
  algorithme/potentiel_solaire/features/solar_exposition.py
  algorithme/potentiel_solaire/features/solar_potential.py
  algorithme/potentiel_solaire/sources/bd_solar_irradiation.py
Labels: enhancement, algorithme

#107 [FRONT] fix: communes api not using updated db schema
  application/app/lib/data.ts
Labels: bug, frontend

#109 [FRONT] feat: update section bonnes pratiques
  .github/pull_request_template.md
  application/README.md
Labels: documentation, frontend

#117 Feature/data 36 amelioration rattachement batiments
  algorithme/notebooks/evaluation_rattachement_batiments_aux_ecoles.ipynb
  algorithme/poetry.lock
  algorithme/potentiel_solaire/attach_buildings_to_schools.py
  algorithme/potentiel_solaire/sources/bd_topo.py
  algorithme/pyproject.toml
Labels: must have, algorithme
